In [1]:
from itertools import product

from tables import *
from entropy import calculate_entropy_unigram, calculate_entropy_bigram

In [21]:
def ent(x):
    if not isinstance (x, torch.Tensor):
        x = torch.tensor(x)
    if x.dtype != torch.float32:
        x = x.float()
    x += x.min()
    x = x.abs()
    x /= x.sum()
    print(x)
    t = -1 * (x * x.log()).sum()
    return t.item()

In [22]:
ent(torch.randn(10))

tensor([0.1109, 0.0872, 0.0975, 0.0616, 0.1436, 0.0708, 0.1869, 0.0745, 0.0539,
        0.1131])


2.232290267944336

In [67]:
ent_to_target = ent(
    tensor(
        [0.1109, 0.0872, 0.0975, 0.0616, 0.1436, 0.0708, 0.1869, 0.0745, 0.0539, 0.1131]
    )
)
ent_to_target

tensor([0.1071, 0.0917, 0.0984, 0.0750, 0.1283, 0.0810, 0.1565, 0.0834, 0.0700,
        0.1085])


2.272552251815796

In [116]:
ent([2.97339, 1, 1, 1, 1, 1, 1, 1, 1, 1])

tensor([0.1808, 0.0910, 0.0910, 0.0910, 0.0910, 0.0910, 0.0910, 0.0910, 0.0910,
        0.0910])


2.272552013397217